### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by abaumhauer** [erickt/rust-serialization-benchmarks#5]
Under the beta version of rust, latest clone of 0.1.8...

cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading libc v0.1.12
 Downloading log v0.3.3
 Downloading compiletest_rs v0.0.10
   Compiling postgres_macros v0.1.8 (file:///root/Projects/rust-postgres-macros)
failed to run custom build command for `postgres_macros v0.1.8 (file:///root/Projects/rust-postgres-macros)`
Process didn't exit successfully: `/root/Projects/rust-postgres-macros/target/debug/build/postgres_macros-7197faef4df57d61/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:738

**Comment by pickfire** [comment]
@abaumhauer I think this should be fixed with the latest nightly compiler.
